name: iOS CI

on:
  push:
    branches: [ "main", "feat/*ios*" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_and_test:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
        
    - name: Generate Xcode project from XcodeGen
      run: |
        brew install xcodegen
        cd apps/ios
        xcodegen generate
        
    - name: Build and Test App (Includes UI and Unit Tests)
      run: |
        cd apps/ios
        xcodebuild test -project Canopy.xcodeproj -scheme CanopyHostApp -destination 'platform=iOS Simulator,name=iPhone 15 Pro,OS=latest'
